# Variables specific to the main_ec2 group
ec2_public_ip: "3.237.76.239"
ec2_user: "ec2-user" 
ssh_private_key_path: "~/.ssh/id_rsa"  # Correct SSH key file that exists

# ec2_public_ip: "{{ host_ip }}"
# ec2_user: "{{ ansible_username }}" 
# ssh_private_key_content: ""

# These variables can be used in playbooks
server_name: "web-server"
deployment_env: "development"

# Application configuration
app_name: "SinkingCloudsCreative"
app_port: 8080
git_repo: "https://github.com/acpcreation/SinkingCloudsCreative.git"