apiVersion: v2
name: nginx-stable
description: A Helm chart for deploying NGINX Ingress Controller
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: nginx-ingress
    version: "1.3.2"
    repository: "https://helm.nginx.com/stable"