# Variables specific to the main_ec2 group
ec2_public_ip: "44.213.119.13"
ec2_user: "ec2-user" 
ssh_private_key_path: "~/.ssh/id_rsa"

# These variables can be used in playbooks
server_name: "web-server"
deployment_env: "development"

# Application configuration
app_name: "SinkingCloudsCreative"
app_port: 8080
git_repo: "https://YOUR_PAT_HERE@github.com/acpcreation/SinkingCloudsCreative.git"